# Generated by Django 4.2.28 on 2026-02-24 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('parameters', models.IntegerField()),
                ('turnaround_hours', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labtests.category')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
                ('reviews', models.IntegerField()),
                ('is_nabl_certified', models.BooleanField(default=False)),
                ('home_collection', models.BooleanField(default=False)),
                ('online_report', models.BooleanField(default=True)),
                ('offline_report', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TestPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('discount_percent', models.IntegerField(default=0)),
                ('report_eta_hours', models.IntegerField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labtests.labtest')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labtests.vendor')),
            ],
        ),
    ]
