# Generated by Django 4.2.28 on 2026-02-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='fasting',
            field=models.BooleanField(default=False),
        ),
    ]
