# Generated by Django 4.2.28 on 2026-02-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labtests', '0002_labtest_fasting'),
    ]

    operations = [
        migrations.AddField(
            model_name='testpricing',
            name='eta',
            field=models.CharField(default='24 hours', max_length=50),
        ),
        migrations.AddField(
            model_name='testpricing',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
